In [2]:
# PYTHON LISTS

In [3]:
a = [1, 4.5, "string", True, 7890234567874345678765, "this is a massive string with a tonne of characters which would take up a lot of space!"]

In [5]:
a # HETEROGENEOUS!

[1,
 4.5,
 'string',
 True,
 7890234567874345678765,
 'this is a massive string with a tonne of characters which would take up a lot of space!']

In [7]:
# NUMPY ONLY HANDLES HOMOGENEOUS DATA! -> Numpy Arrays

In [8]:
import math as m

In [9]:
m.log(10)

2.302585092994046

In [10]:
a = [1,2,3,4,5]

In [12]:
import numpy as np

In [13]:
res = [ i ** 2 for i in a ]

In [14]:
res

[1, 4, 9, 16, 25]

In [16]:
b = np.array(a)

In [17]:
b

array([1, 2, 3, 4, 5])

In [19]:
type(b) # n - dimensional array

numpy.ndarray

In [20]:
a

[1, 2, 3, 4, 5]

In [21]:
# Numpy arrays support element wise operations

In [22]:
b

array([1, 2, 3, 4, 5])

In [23]:
a ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [24]:
b ** 2

array([ 1,  4,  9, 16, 25])

In [26]:
a

[1, 2, 3, 4, 5]

In [25]:
%timeit [i**2 for i in a]

1.37 µs ± 5.29 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [28]:
%timeit [i ** 3 for i in range(100000)]

30.6 ms ± 310 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [29]:
l = np.array(range(100000))

In [30]:
%timeit l ** 3

135 µs ± 458 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [31]:
'''
Why is numpy so fast?
- Homogeneous
- Divide tasks in parallel processes
- Numpy functions are directly implemented in C
'''

'\nWhy is numpy so fast?\n- Homogeneous\n- Divide tasks in parallel processes\n- Numpy functions are directly implemented in C\n'

In [32]:
a = np.array(range(10000))

In [33]:
a.ndim # tells how many dimensions there are in the array

1

In [34]:
a.shape

(10000,)

In [39]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [40]:
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [41]:
b.ndim

2

In [42]:
b.shape

(4, 3)

In [43]:
a = np.array([1,2,3,4,5,6,7,8])

In [44]:
a.ndim

1

In [45]:
a.shape

(8,)

In [47]:
# np.arange(start, end, step_size) # THIS HAS A SINGLE "r"

In [48]:
a1 = np.arange(1, 5) # default step size is 1

In [49]:
a1

array([1, 2, 3, 4])

In [50]:
a2 = np.arange(1, 5, 2)

In [51]:
a2

array([1, 3])

In [52]:
# np.arange can also work with float values!

In [53]:
a3 = np.arange(1, 5, 0.5)

In [54]:
a3

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [55]:
1.

1.0

In [56]:
a3

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [57]:
a3[0]

1.0

In [58]:
a3[-1]

4.5

In [59]:
a3[2:5]

array([2. , 2.5, 3. ])

In [60]:
a = [1,2,3,4,5.6]

In [61]:
a = np.array(a)

In [62]:
a

array([1. , 2. , 3. , 4. , 5.6])

In [63]:
b = np.array(["bipin kalra", 1, 2, 3, 4, 5])

In [64]:
b

array(['bipin kalra', '1', '2', '3', '4', '5'], dtype='<U21')

In [68]:
c = np.array([1,2,3,4])

In [69]:
c

array([1, 2, 3, 4])

In [67]:
# Intrinsic Typecasting -> Happens Automatically
# Extrinsic Typecasting -> Manually based on user preference

In [70]:
d = np.array([1,2,3,4], dtype = "float")

In [71]:
d

array([1., 2., 3., 4.])

In [72]:
e = np.array(["this", "is", "absurd!"], dtype = "float")

ValueError: could not convert string to float: 'this'

In [73]:
# FANCY INDEXING

In [74]:
m1 = np.array(range(1,11))

In [75]:
m1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
m1 < 6

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [77]:
a = [1,2,3,4,5]

In [79]:
a[1,2,4] # Fetching elements at multiple indexes at the same time is not possible in lists

TypeError: list indices must be integers or slices, not tuple

In [80]:
# IT IS POSSIBLE IN NUMPY ARRAYS

In [81]:
m1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
m1[[1,5,3,4]]

array([2, 6, 4, 5])

In [85]:
m1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
m1[m1 % 2 == 0]

array([ 2,  4,  6,  8, 10])

In [88]:
m1 % 2 == 0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [89]:
'''
BREADOWN ->
-> [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]
-> [False, True, False, True, False, True, False, True, False, True]
'''

'\nBREADOWN ->\n-> [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]\n-> [False, True, False, True, False, True, False, True, False, True]\n'

In [91]:
np.array([[1],[2,3],[4,5,6],[7,8,9,10]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

# NPS CASE

In [90]:
!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK

zsh:1: command not found: gdown
