# 2D ARRAYS

In [3]:
import numpy as np

In [4]:
a = np.array(range(16))

In [5]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [6]:
a.shape

(16,)

In [7]:
a.ndim

1

In [8]:
# np_array.reshape(num_rows, num_columns)

In [10]:
a.reshape(8, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [11]:
a.reshape(4, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
a.reshape(4, 5)

ValueError: cannot reshape array of size 16 into shape (4,5)

In [13]:
a.reshape(8, -1)
# -1 denotes that you want python to automatically calculate the second argument

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [14]:
a.reshape(-1, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [16]:
a.reshape(-1, -1) # AMBIGUITY

ValueError: can only specify one unknown dimension

In [17]:
a = a.reshape(8, 2)

In [18]:
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [21]:
len(a) # number of rows

8

In [22]:
len(a[0]) # number of columns

2

In [29]:
a = np.arange(12)

In [30]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
a = a.reshape(3, 4)

In [32]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
# FUNCTION CHAINING

b = np.arange(12).reshape(3, 4)

In [36]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
b.shape

(3, 4)

In [38]:
b.T # T represents the transpose of any matrix in numpy

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [39]:
b.T.shape

(4, 3)

In [40]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
b[0][1] # np_array[row_number][col_number]

1

In [43]:
b[0, 1] # This only works with numpy arrays -> NOT WITH PYTHON LISTS

1

In [44]:
c = np.arange(9).reshape(3, 3)

In [45]:
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
d = np.arange(10)

In [47]:
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
d[[6,7,8,1]]

array([6, 7, 8, 1])

In [50]:
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
c[[0,1,2],[0,1,2]] # [c[0][0], c[1][1], c[2][2]]

array([0, 4, 8])

In [54]:
c[[0,2],[1,5]] # This index is out of range

IndexError: index 5 is out of bounds for axis 1 with size 3

In [55]:
c[[1,2,0],[1,2]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [56]:
test = np.arange(64).reshape(8,8)

In [57]:
test

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [59]:
test[list(range(len(test))),list(range(len(test)))]

array([ 0,  9, 18, 27, 36, 45, 54, 63])

In [60]:
# BY DEFAULT SLICING IS DONE ON ROWS

In [61]:
a = np.arange(12).reshape(3, 4)

In [62]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
a[:2] # This slice got applied to rows and we got all columns

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [66]:
a[:, 1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [67]:
a[:2, 1:3]

array([[1, 2],
       [5, 6]])

In [68]:
test

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [70]:
test[3:7:2, 1:6:3] # Step Size also works when slicing 2D arrays

array([[25, 28],
       [41, 44]])

In [72]:
a = np.array([1,2,3,4,5])
b = np.array([8,7,6])

In [73]:
a[3:]

array([4, 5])

In [74]:
b[::-2]

array([6, 8])

In [75]:
a[3:] = b[::-2]

In [76]:
a

array([1, 2, 3, 6, 8])

In [78]:
a = np.arange(12).reshape(4,3)

In [79]:
a[a < 6]

array([0, 1, 2, 3, 4, 5])

In [80]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [81]:
a < 6

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False],
       [False, False, False]])

# Aggregate Functions

In [83]:
a = np.arange(1, 11)

In [84]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
np.sum(a)

55

In [86]:
np.mean(a)

5.5

In [87]:
np.min(a)

1

In [88]:
np.max(a)

10

In [89]:
a = np.arange(12).reshape(3, 4)

In [90]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
np.sum(a)

66

In [92]:
np.sum(a, axis = 0)

array([12, 15, 18, 21])

In [93]:
np.sum(a, axis = 1)

array([ 6, 22, 38])

# Logical Operations

In [95]:
prices = np.array([50, 45, 25, 20, 35])

In [96]:
can_afford = np.any(prices <= 30)
# Returns True if the condition is True for even a single value

In [97]:
can_afford

True

In [98]:
task_completion = np.array([1,1,1,1,1,1,0])

In [99]:
can_go_out_play = np.all(task_completion == 1)
# Returns True if all the values satisfy the condition

In [100]:
can_go_out_play

False

In [111]:
a = np.array([1,4,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])

In [115]:
((a <= b) & (b <= c)).all()

False

In [116]:
a = np.array([-3,4,27,34,-2, 0, -45,-11,4, 0 ])
a

array([ -3,   4,  27,  34,  -2,   0, -45, -11,   4,   0])

In [119]:
a[a > 0] = 1
a[a < 0] = -1

# Setting values for elements selected via fancy indexing

In [120]:
a

array([-1,  1,  1,  1, -1,  0, -1, -1,  1,  0])

In [121]:
# np.where(condition, value_if_true, value_if_false)

In [122]:
prices = np.array([45, 55, 60, 30, 75, 20, 100, 90])

In [123]:
discounted_prices = np.where(prices > 50, prices * 0.9, prices)

In [124]:
discounted_prices

array([45. , 49.5, 54. , 30. , 67.5, 20. , 90. , 81. ])

In [125]:
a = [1,2,3,4,5,6,7,8]

In [126]:
a[3:7:2]

[4, 6]

In [127]:
a[1:6:3]

[2, 5]