In [ ]:
import numpy as np

### Quiz: Refresh old concept

```

arr = np.arange(12)

arr = arr.reshape(-1,4)

What will the shape of array ?

A. (-1, 4)
B. (12,)
C. (3, 4)
D. (1, 12)

```

In [ ]:
arr = np.arange(12)

arr = arr.reshape(-1,4)

arr.shape

(3, 4)

In [ ]:
#sort

In [ ]:
a = np.array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])
a

array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])

In [ ]:
b = np.sort(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
print(a)

[4 7 0 3 8 2 5 1 6 9]


In [ ]:
d = a

In [ ]:
d

array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])

In [ ]:
d.sort()
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#argsort()

In [ ]:
a = np.array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])
a

array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])

In [ ]:
a.argsort()

array([2, 7, 5, 3, 0, 6, 8, 1, 4, 9])

In [ ]:
b = np.array([5,7,3,1,10])
b.argsort()

array([3, 2, 0, 1, 4])

### Quiz: Ufunc Sorting

```
a = np.array([[23,4,43],
              [12,89,3],
              [69,420,0]])

b = np.sort(a)

What'll be value of b?

a. Error
b. [[  0,   3,   4],
    [ 12,  23,  43],
    [ 69,  89, 420]]

c. [[  4,  23,  43],
    [  3,  12,  89],
    [  0,  69, 420]]

d. [[  0,  12,  43],
    [  3,  23,  89],
    [  4,  69, 420]]
    

```

In [ ]:
a = np.array([[23,4,43],
              [12,89,3],
              [69,420,0]])

b = np.sort(a)
print(b)

[[  4  23  43]
 [  3  12  89]
 [  0  69 420]]


In [ ]:
#element wise operations

In [ ]:
a = np.arange(5)
b = np.ones(5)
print(a)

[0 1 2 3 4]


In [ ]:
print(b)

[1. 1. 1. 1. 1.]


In [ ]:
#element-wise operations
a*b

array([0., 1., 2., 3., 4.])

In [ ]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b = np.arange(2,14).reshape(3,4)
b

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [ ]:
a*b

array([[  2,   6,  12,  20],
       [ 30,  42,  56,  72],
       [ 90, 110, 132, 156]])

In [ ]:
#Matrix Multiplication

'''
1. np.dot
2. @ operator
3. np.matmul
'''

In [ ]:
a = np.arange(1, 13).reshape(3,4)
b = np.arange(2,14).reshape(4,3)

In [ ]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(b)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


In [ ]:
a.shape

(3, 4)

In [ ]:
b.shape

(4, 3)

In [ ]:
np.dot(a,b)

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [ ]:
a@b

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [ ]:
np.matmul(a,b)

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

#### Quiz
```
What will be the shape of the output?

A = np.arange(10).reshape(5,2)

B = np.arange(2).reshape(2,1)

print(np.dot(A,B))

```

```
A. Error

B. (5,2)

C. (5,)

D. (5,1)

```

In [ ]:
A = np.arange(10).reshape(5,2)
print(A)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
B = np.arange(2).reshape(2,1)
print(B)

[[0]
 [1]]


In [ ]:
C = np.dot(A,B)

In [ ]:
C.shape

(5, 1)

In [ ]:
d = np.arange(5)

In [ ]:
d.shape

(5,)

In [ ]:
len(d)

5

In [ ]:
#vectorization

In [ ]:
a = np.arange(1,13)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


* 1d np array --> vector
* 2d np array --> matrix
* 3d onwards --> tensors

In [ ]:
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [ ]:
def solve(x):
  if x%2 == 0:
    x = x*2
  else:
    x = x*3

  return x

In [ ]:
solve(5)

15

In [ ]:
solve(6)

12

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
aj_func = np.vectorize(solve)

In [ ]:
solve(a)

ValueError: ignored

In [ ]:
aj_func(a)

array([ 3,  4,  9,  8, 15, 12, 21, 16, 27, 20, 33, 24])

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
import math
vectorized_log = np.vectorize(math.log)


In [ ]:
vectorized_log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665])

In [ ]:
b = np.arange(1,10).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
aj_func(b)

array([[ 3,  4,  9],
       [ 8, 15, 12],
       [21, 16, 27]])

In [ ]:
#broadcasting

![bro.jpg](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/047/364/original/download.jpeg?1694345633)

In [ ]:
a = np.arange(0,40,10)

In [ ]:
a

array([ 0, 10, 20, 30])

In [ ]:
a = np.tile(a, (3,1))
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]


In [ ]:
b = np.arange(0,3)

In [ ]:
b

array([0, 1, 2])

In [ ]:
b = np.tile(np.arange(0,3), (4,1))

In [ ]:
b

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [ ]:
b.shape

(4, 3)

In [ ]:
a.shape

(3, 4)

In [ ]:
a = a.T
a.shape

(4, 3)

In [ ]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [ ]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [ ]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [ ]:
b = np.arange(0,3)

In [ ]:
a.shape, b.shape

((4, 3), (3,))

In [ ]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [ ]:
b

array([0, 1, 2])

In [ ]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [ ]:
a = np.arange(0,40,10).reshape(4,1)
a

array([[ 0],
       [10],
       [20],
       [30]])

In [ ]:
b = np.arange(0,3)

In [ ]:
b

array([0, 1, 2])

In [ ]:
a.shape, b.shape

((4, 1), (3,))

In [ ]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [ ]:
#Quiz

In [ ]:
a = np.arange(8).reshape(2,4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
b = np.arange(16).reshape(4,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
a + b

ValueError: ignored

In [ ]:
A = np.arange(1,10).reshape(3,3)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
B = np.array([-1, 0, 1])
B

array([-1,  0,  1])

In [ ]:
A*B

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

#### Quiz
```
A = np.arange(12).reshape(3, 4)
B = np.array([1, 2, 3])



What'll be the output of A + B ?


A. [[0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11]]

B. Error

C. [[1, 2, 3, 4],
    [6, 7, 8, 9],
    [11,12,13,14]]
```

In [ ]:
A = np.arange(12).reshape(3, 4)
B = np.array([1, 2, 3])
A+B

ValueError: ignored

#### Quiz-6 Broadcasting shape


```
Given two arrays of shape

1. Array A of shape  (8, 1, 6, 1)
2. Array B of shape (7, 1, 5)

Is broadcasting possible in this case? If yes, what will be the shape of output ?

A. Broadcasting not possible as dimensions don't match
B. Broadcasting not possible as dimension value 6 and 5 doesn't match
C. Broadcasting possible. Shape will be (8, 1, 6, 5)
D. Broadcasting possible; Shape will be (8, 7, 6, 5)


```

Doubts

In [ ]:
a= np.array([[4,2],
             [1,5]])

a

array([[4, 2],
       [1, 5]])

In [ ]:
np.sort(a, axis = 0)

array([[1, 2],
       [4, 5]])

In [ ]:
np.sort(a, axis = 1)

array([[2, 4],
       [1, 5]])