In [1]:
import numpy as np

In [2]:
a = np.arange(4)

In [3]:
a

array([0, 1, 2, 3])

In [4]:
b = a.reshape(2, 2)

In [5]:
b

array([[0, 1],
       [2, 3]])

In [6]:
a[0] = 100

In [7]:
a

array([100,   1,   2,   3])

In [8]:
b

array([[100,   1],
       [  2,   3]])

In [9]:
# NUMPY CREATES A SHALLOW COPY WHEN RESHAPING

In [10]:
np.shares_memory(a, b)

True

In [11]:
a = np.arange(4)

In [12]:
c = a + 2

In [13]:
a

array([0, 1, 2, 3])

In [14]:
c

array([2, 3, 4, 5])

In [15]:
np.shares_memory(a, c)

False

In [16]:
c[0] = 100

In [17]:
c

array([100,   3,   4,   5])

In [18]:
a

array([0, 1, 2, 3])

In [19]:
a = np.array([0,0,0,0])

In [20]:
a

array([0, 0, 0, 0])

In [21]:
b = a * 2

In [23]:
a, b

(array([0, 0, 0, 0]), array([0, 0, 0, 0]))

In [22]:
np.shares_memory(a, b)

False

In [24]:
a = np.arange(10)

In [25]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
b = a[::2]

In [27]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
b

array([0, 2, 4, 6, 8])

In [29]:
np.shares_memory(a, b)

True

In [30]:
b[0] = 1000

In [31]:
a

array([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [33]:
0 % 1

0

In [34]:
a = np.arange(6)
b = a[a%1 == 0]
b[0] = 10

In [35]:
a

array([0, 1, 2, 3, 4, 5])

In [36]:
b

array([10,  1,  2,  3,  4,  5])

In [37]:
np.shares_memory(a, b)

False

In [38]:
'''
Shallow Copy -> Reshaping, Slicing...
Deep Copy -> Arithmetic Operations, Masking...
'''

'\nShallow Copy -> Reshaping, Slicing...\nDeep Copy -> Arithmetic Operations, Masking...\n'

In [39]:
a = np.arange(10)

In [41]:
a_shallow_copy = a.view() # Creates a shallow copy of a

In [42]:
np.shares_memory(a, a_shallow_copy)

True

In [43]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
a_shallow_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
a_shallow_copy[0] = 100

In [46]:
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [47]:
a = np.arange(10)

In [48]:
a_deep_copy = a.copy() # Creates a deep copy of a

In [49]:
np.shares_memory(a, a_deep_copy)

False

#### `.copy()`

Returns copy of the array.

Documentation (`.copy()`): https://numpy.org/doc/stable/reference/generated/numpy.ndarray.copy.html#numpy.ndarray.copy

Documentation: (`np.copy()`): https://numpy.org/doc/stable/reference/generated/numpy.copy.html

In [56]:
a = np.array([10,15,25,5,20,0,30])

In [57]:
a_sorted = np.sort(a)

In [58]:
a

array([10, 15, 25,  5, 20,  0, 30])

In [59]:
a_sorted

array([ 0,  5, 10, 15, 20, 25, 30])

In [60]:
b = a.copy()

In [61]:
b.sort()

In [62]:
b

array([ 0,  5, 10, 15, 20, 25, 30])

In [63]:
a

array([10, 15, 25,  5, 20,  0, 30])

# Splitting Data

In [64]:
a = np.arange(9)

In [65]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [66]:
# Splitting in n sections

In [67]:
np.split(a, 3) # np.split(array, number_of_sections)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [68]:
b = np.arange(14)

In [69]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [70]:
np.split(b, 3)

ValueError: array split does not result in an equal division

In [71]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [73]:
# Splitting on the basis of exact indexes

In [74]:
np.split(b, [3, 5, 9]) # np.split(array, [list_of_indexes])

[array([0, 1, 2]),
 array([3, 4]),
 array([5, 6, 7, 8]),
 array([ 9, 10, 11, 12, 13])]

In [75]:
a = np.arange(10)

In [76]:
z = a[-1]

In [77]:
z

9

In [79]:
w, x, y = np.split(a[0:-1], 3)

In [80]:
w

array([0, 1, 2])

In [81]:
x

array([3, 4, 5])

In [82]:
y

array([6, 7, 8])

In [83]:
a = np.arange(36).reshape(6,6)

In [84]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [85]:
np.hsplit(a, 3)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25],
        [30, 31]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27],
        [32, 33]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29],
        [34, 35]])]

In [88]:
np.hsplit(a, [2,5])

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25],
        [30, 31]]),
 array([[ 2,  3,  4],
        [ 8,  9, 10],
        [14, 15, 16],
        [20, 21, 22],
        [26, 27, 28],
        [32, 33, 34]]),
 array([[ 5],
        [11],
        [17],
        [23],
        [29],
        [35]])]

In [89]:
np.hsplit(a, [2,5,1000])

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25],
        [30, 31]]),
 array([[ 2,  3,  4],
        [ 8,  9, 10],
        [14, 15, 16],
        [20, 21, 22],
        [26, 27, 28],
        [32, 33, 34]]),
 array([[ 5],
        [11],
        [17],
        [23],
        [29],
        [35]]),
 array([], shape=(6, 0), dtype=int64)]

In [90]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [91]:
np.vsplit(a, 2)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [92]:
np.vsplit(a, [1, 4])

[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

# Stacking

In [93]:
data = np.arange(5)

In [94]:
data

array([0, 1, 2, 3, 4])

In [97]:
np.vstack([data, data, data])

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [98]:
a = np.arange(1,5)
b = np.arange(2,6)
c = np.arange(3,7)

In [99]:
np.vstack([a, b, c])

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [100]:
a = np.arange(1,5)
b = np.arange(2,4)
c = np.arange(3,10)

In [101]:
np.vstack([a, b, c])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 2

In [102]:
a = np.arange(1,5)

In [103]:
a

array([1, 2, 3, 4])

In [104]:
b = np.arange(16).reshape(4,4)

In [105]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [108]:
np.vstack([b, a])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 1,  2,  3,  4]])

In [109]:
a = np.arange(5).reshape(5, 1)

In [110]:
a

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [111]:
b = np.arange(15).reshape(5, 3)

In [112]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [114]:
np.hstack([a, b])

array([[ 0,  0,  1,  2],
       [ 1,  3,  4,  5],
       [ 2,  6,  7,  8],
       [ 3,  9, 10, 11],
       [ 4, 12, 13, 14]])

In [120]:
# CONCATENATE
# Both the arrays should have the same number of dimensions

In [121]:
a = np.array([1,2,3])
b = np.array([[1,2,3], [4,5,6]])

In [122]:
a

array([[1, 2, 3]])

In [123]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [119]:
np.concatenate([a, b], axis = 0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [124]:
a = np.array([[1,2,3]])
b = np.array([[1,2,3], [4,5,6]])

In [125]:
np.concatenate([a,b], axis = 0)

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [126]:
'''
Concatenate ->
    - Number of dimensions must be same
    - Axis - 
        - vstack -> axis = 0
        - hstack -> axis = 1
'''

'\nConcatenate ->\n    - Number of dimensions must be same\n    - Axis - \n        - vstack -> axis = 0\n        - hstack -> axis = 1\n'

In [127]:
a = np.arange(4).reshape(2,2)
b = np.arange(8).reshape(2,4)

In [128]:
a

array([[0, 1],
       [2, 3]])

In [129]:
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [130]:
np.concatenate([b, a], axis = 1)

array([[0, 1, 2, 3, 0, 1],
       [4, 5, 6, 7, 2, 3]])

In [131]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6]])

In [132]:
np.concatenate([a, b], axis = None)

array([1, 2, 3, 4, 5, 6])

In [133]:
np.flatten([[[[1,2,3]],[2,3,4,5,5,6,6]]])

AttributeError: module 'numpy' has no attribute 'flatten'

In [135]:
a = np.array([[1,2,3],[5,6,7],[8,9,10]])

In [136]:
a.flatten()

array([ 1,  2,  3,  5,  6,  7,  8,  9, 10])