In [2]:
import numpy as np

In [5]:
np.linspace(1, 40, num = 40)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40.])

In [6]:
a = np.arange(4).reshape(2, 2)

In [7]:
a

array([[0, 1],
       [2, 3]])

In [8]:
b = np.array([4,5])

In [11]:
c = np.vstack([a, b])

In [12]:
a

array([[0, 1],
       [2, 3]])

In [13]:
c

array([[0, 1],
       [2, 3],
       [4, 5]])

In [16]:
c.shape[1]

2

In [17]:
[0]*c.shape[1]

[0, 0]

In [20]:
np.zeros(5, dtype = "int")

array([0, 0, 0, 0, 0])

In [36]:
def add_padding(a):
    num_col = a.shape[1]
    
    result = a.copy()
    
    result = np.vstack([
        np.zeros(num_col, dtype = "int"),
        a,
        np.zeros(num_col, dtype = "int")
    ])
    
    num_row = result.shape[0]
    
    # Reshaping to match number of dimensions
    result = np.hstack([
        np.zeros(num_row, dtype = "int").reshape(num_row, 1),
        result,
        np.zeros(num_row, dtype = "int").reshape(num_row, 1)
    ])
    
    return result

In [37]:
random = add_padding(c)

In [38]:
random

array([[0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 2, 3, 0],
       [0, 4, 5, 0],
       [0, 0, 0, 0]])

In [40]:
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [43]:
def add_padding_2(a):
    num_row = a.shape[0]
    num_col = a.shape[1]
    result = np.zeros([num_row + 2, num_col + 2], dtype = "int")
    
    result[1:num_row + 1, 1:num_col + 1] = a
    
    return result

In [44]:
add_padding_2(c)

array([[0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 2, 3, 0],
       [0, 4, 5, 0],
       [0, 0, 0, 0]])

In [47]:
a.shape[1]

2

In [57]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([1,1,1])

In [58]:
a * b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
np.dot(a, b)

array([ 6, 15, 24])

In [60]:
np.matmul(a, b)

array([ 6, 15, 24])

In [61]:
a @ b

array([ 6, 15, 24])

In [73]:
bird_names = np.array(['sparrow', 'peacock', 'parrot', 'owl', 'peacock', 'macaw', 'macaw', 'parrot', 'macaw', 'peacock'])
ages = np.array([6, 1, 6, 5, 7, 6, 0, 9, 0, 7])

In [74]:
np.max(ages)

9

In [75]:
np.argmax(ages)
# returns the index at which the max (largest) element is present

7

In [76]:
bird_names[np.argmax(ages)]

'parrot'

In [79]:
bird_names = ['parrot', 'owl', 'macaw', 'macaw', 'owl', 'owl', 'macaw', 'macaw', 'sparrow', 'owl', 'sparrow', 'parrot', 'macaw', 'peacock', 'sparrow', 'macaw', 'peacock', 'owl', 'owl', 'parrot']
ages = [8, 1, 12, 13, 13, 8, 11, 7, 6, 1, 7, 4, 12, 6, 1, 8, 14, 13, 14, 1]

In [80]:
bird_names[np.argmax(ages)]

'peacock'

In [81]:
list("string")

['s', 't', 'r', 'i', 'n', 'g']

In [84]:
"string".split("")

ValueError: empty separator

In [86]:
x = np.zeros([5,5])

In [87]:
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [88]:
x[1:-1, 1:-1] = 0

In [89]:
a = np.arange(1, 11)

In [90]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
a <= 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [92]:
a[a <= 5]

array([1, 2, 3, 4, 5])

In [93]:
v = np.array([200,300,400])

In [97]:
v[:, None] # WEIRD NUMPY BEHAVIOUR

array([[200],
       [300],
       [400]])

In [98]:
v.reshape(-1, 1)

array([[200],
       [300],
       [400]])

In [ ]:
import numpy as np
x = np.array([[200,200,200],[300,300,300],[400,400,400]])
v = np.array([200,300,400])
print((x / v[:,None])[1][1])